FROM public.ecr.aws/docker/library/node:22.16.0-bullseye AS origin

FROM origin AS builder
WORKDIR /app
COPY . .

FROM origin AS runner

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/dist .

EXPOSE 80

CMD [ "node", "index.js" ]